# Generated by Django 5.2 on 2025-05-14 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordingsessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordingsession',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recordingsession',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на конференцию'),
        ),
        migrations.AddField(
            model_name='recordingsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
