# Generated by Django 5.2 on 2025-05-08 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0003_recordingsession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecordingSession',
        ),
    ]
