# Generated by Django 5.2 on 2025-04-14 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recordings', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recording', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='recordings.recording')),
            ],
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recording', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcript', to='recordings.recording')),
            ],
        ),
    ]
