# Generated by Django 5.2 on 2025-05-06 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0001_initial'),
        ('recordings', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summary',
            old_name='summary_text',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='recording',
        ),
        migrations.RemoveField(
            model_name='transcript',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='transcript',
            name='recording',
        ),
        migrations.AddField(
            model_name='transcript',
            name='timestamps',
            field=models.JSONField(null=True),
        ),
        migrations.CreateModel(
            name='VideoJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает'), ('RUNNING', 'В процессе'), ('SUCCESS', 'Успешно'), ('FAILED', 'Ошибка')], default='PENDING', max_length=10)),
                ('log', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='recordings.recording')),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='processing.videojob')),
            ],
        ),
        migrations.AddField(
            model_name='summary',
            name='job',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='processing.videojob'),
        ),
        migrations.AddField(
            model_name='transcript',
            name='job',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transcript', to='processing.videojob'),
        ),
    ]
